In [2]:
import pandas as pd
import numpy as np

In [3]:
dfo = pd.read_csv('dfo_masterlist.csv', encoding='latin1')
emdat = pd.read_csv('historical_dataset.csv', encoding='latin1')

In [6]:
dfo.head()

,Register__,Annual_DFO,Glide__,Country__c,Other,Nations,Affected,Detailed_L,Rivers,Began,...,Total_an_1,Date_Began,Total_floo,Total_fl_1,F31,F32,F33,F34,F35,F36
0,3703.0,114.0,NaN,Niger,Burkina Faso,Chad,NaN,"Niamey, northern Chad",NaN,2010-08-01,...,259.0,2010-08-01,896.0,3171.0,NaN,NaN,NaN,NaN,NaN,NaN
1,3702.0,113.0,NaN,United States,NaN,NaN,NaN,"State of Iowa, Ames, Colfax towns",NaN,2010-08-10,...,258.0,2010-08-10,895.0,3170.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3701.0,112.0,NaN,North Korea,NaN,NaN,NaN,"Eastern province of South Hamkyong, northweste...",NaN,2010-07-27,...,257.0,2010-07-27,895.0,3169.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3700.0,111.0,NaN,India,NaN,NaN,NaN,"Kashmir,",NaN,2010-08-06,...,256.0,2010-08-06,895.0,3168.0,NaN,NaN,NaN,NaN,NaN,NaN
4,3699.0,110.0,NaN,China,NaN,NaN,NaN,Entire communities in Gansu province's Zhouqu ...,NaN,2010-07-27,...,255.0,2010-07-27,894.0,3167.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
emdat.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2025-0303-ECU,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,ECU,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-04-28,2026-05-15
1,2026-0153-KEN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,KEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-09,2026-05-15
2,2025-0750-AFG,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2025-000153,NaN,AFG,...,NaN,NaN,NaN,180000.0,180000.0,100.0,NaN,NaN,2025-09-01,2026-05-15
3,2026-0305-AFG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,AFG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-04,2026-05-11
4,2024-0962-AGO,No,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,GLIDE:EP-2025-000013,Cholera,AGO,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-01-17,2026-05-15