In [2]:
import pandas as pd
import numpy as np

In [3]:
dfo = pd.read_csv('dfo_masterlist.csv', encoding='latin1')
emdat = pd.read_csv('historical_dataset.csv', encoding='latin1')

In [4]:
dfo.head()

,Register__,Annual_DFO,Glide__,Country__c,Other,Nations,Affected,Detailed_L,Rivers,Began,...,Total_an_1,Date_Began,Total_floo,Total_fl_1,F31,F32,F33,F34,F35,F36
0,3703.0,114.0,NaN,Niger,Burkina Faso,Chad,NaN,"Niamey, northern Chad",NaN,2010-08-01,...,259.0,2010-08-01,896.0,3171.0,NaN,NaN,NaN,NaN,NaN,NaN
1,3702.0,113.0,NaN,United States,NaN,NaN,NaN,"State of Iowa, Ames, Colfax towns",NaN,2010-08-10,...,258.0,2010-08-10,895.0,3170.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3701.0,112.0,NaN,North Korea,NaN,NaN,NaN,"Eastern province of South Hamkyong, northweste...",NaN,2010-07-27,...,257.0,2010-07-27,895.0,3169.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3700.0,111.0,NaN,India,NaN,NaN,NaN,"Kashmir,",NaN,2010-08-06,...,256.0,2010-08-06,895.0,3168.0,NaN,NaN,NaN,NaN,NaN,NaN
4,3699.0,110.0,NaN,China,NaN,NaN,NaN,Entire communities in Gansu province's Zhouqu ...,NaN,2010-07-27,...,255.0,2010-07-27,894.0,3167.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
emdat.head(10)

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2025-0303-ECU,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,ECU,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-04-28,2026-05-15
1,2026-0153-KEN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,KEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-09,2026-05-15
2,2025-0750-AFG,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2025-000153,NaN,AFG,...,NaN,NaN,NaN,180000.0,180000.0,100.0,NaN,NaN,2025-09-01,2026-05-15
3,2026-0305-AFG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,AFG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-04,2026-05-11
4,2024-0962-AGO,No,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,GLIDE:EP-2025-000013,Cholera,AGO,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-01-17,2026-05-15
5,2025-9122-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SOM,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-02-26,2026-05-15
6,2026-0174-SYR,No,nat-met-sto-sev,Natural,Meteorological,Storm,Severe weather,NaN,NaN,SYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-18,2026-05-15
7,1988-0424-VEN,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Hurricane 'Gilbert',VEN,...,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,NaN,2026-05-12,2026-05-12
8,2025-0272-KGZ,No,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,GLIDE:EP-2025-000030|GLIDE:EP-2025-000105,Measles & Rubella,KGZ,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-04-16,2026-05-20
9,2026-0227-BGD,No,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,GLIDE:EP-2026-000048,Meales,BGD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-07,2026-05-20

In [6]:
dfo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4029 entries, 0 to 4028
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Register__  4029 non-null   float64
 1   Annual_DFO  4029 non-null   float64
 2   Glide__     342 non-null    str
 3   Country__c  3703 non-null   str
 4   Other       299 non-null    str
 5   Nations     102 non-null    str
 6   Affected    0 non-null      float64
 7   Detailed_L  3625 non-null   str
 8   Rivers      1847 non-null   str
 9   Began       3703 non-null   str
 10  Ended       3703 non-null   str
 11  Duration_i  4029 non-null   float64
 12  Dead        4029 non-null   float64
 13  Displaced   4029 non-null   float64
 14  Damage__US  4029 non-null   float64
 15  Main_cause  3647 non-null   str
 16  Severity__  4029 non-null   float64
 17  Affected_s  4029 non-null   float64
 18  Magnitude   4029 non-null   float64
 19  Centroid_X  4029 non-null   float64
 20  Centroid_Y  4029 non-null   float64
 21  "x"_if_act  11 non-null     str
 22  M_6         4029 non-null   float64
 23  Total_annu  4029 non-null   float64
 24  M_4         4029 non-null   float64
 25  Total_an_1  4029 non-null   float64
 26  Date_Began  3703 non-null   str
 27  Total_floo  4029 non-null   float64
 28  Total_fl_1  4029 non-null   float64
 29  F31         0 non-null      float64
 30  F32         0 non-null      float64
 31  F33         0 non-null      float64
 32  F34         0 non-null      float64
 33  F35         0 non-null      float64
 34  F36         0 non-null      float64
dtypes: float64(24), str(11)
memory usage: 1.1 MB

In [7]:
emdat.info()

<class 'pandas.DataFrame'>
RangeIndex: 16913 entries, 0 to 16912
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     16913 non-null  str
 1   Historic                                   16913 non-null  str
 2   Classification Key                         16913 non-null  str
 3   Disaster Group                             16913 non-null  str
 4   Disaster Subgroup                          16913 non-null  str
 5   Disaster Type                              16913 non-null  str
 6   Disaster Subtype                           16913 non-null  str
 7   External IDs                               4391 non-null   str
 8   Event Name                                 5365 non-null   str
 9   ISO                                        16913 non-null  str
 10  Country                                    16913 non-null  str
 11  Subregion                                  16913 non-null  str
 12  Region                                     16913 non-null  str
 13  Location                                   16115 non-null  str
 14  Origin                                     4328 non-null   str
 15  Associated Types                           3710 non-null   str
 16  OFDA/BHA Response                          16913 non-null  str
 17  Appeal                                     16913 non-null  str
 18  Declaration                                16913 non-null  str
 19  AID Contribution ('000 US$)                489 non-null    float64
 20  Magnitude                                  3403 non-null   float64
 21  Magnitude Scale                            10624 non-null  str
 22  Latitude                                   1861 non-null   float64
 23  Longitude                                  1861 non-null   float64
 24  River Basin                                1349 non-null   str
 25  Start Year                                 16913 non-null  int64
 26  Start Month                                16839 non-null  float64
 27  Start Day                                  15321 non-null  float64
 28  End Year                                   16913 non-null  int64
 29  End Month                                  16742 non-null  float64
 30  End Day                                    15406 non-null  float64
 31  Total Deaths                               13630 non-null  float64
 32  No. Injured                                6368 non-null   float64
 33  No. Affected                               7866 non-null   float64
 34  No. Homeless                               1366 non-null   float64
 35  Total Affected                             12637 non-null  float64
 36  Reconstruction Costs ('000 US$)            34 non-null     float64
 37  Reconstruction Costs, Adjusted ('000 US$)  34 non-null     float64
 38  Insured Damage ('000 US$)                  724 non-null    float64
 39  Insured Damage, Adjusted ('000 US$)        721 non-null    float64
 40  Total Damage ('000 US$)                    3342 non-null   float64
 41  Total Damage, Adjusted ('000 US$)          3314 non-null   float64
 42  CPI                                        16697 non-null  float64
 43  Admin Units                                8394 non-null   str
 44  GADM Admin Units                           7831 non-null   str
 45  Entry Date                                 16913 non-null  str
 46  Last Update                                16913 non-null  str
dtypes: float64(20), int64(2), str(25)
memory usage: 6.1 MB

In [8]:
dfo.isnull().sum()

Register__       0
Annual_DFO       0
Glide__       3687
Country__c     326
Other         3730
Nations       3927
Affected      4029
Detailed_L     404
Rivers        2182
Began          326
Ended          326
Duration_i       0
Dead             0
Displaced        0
Damage__US       0
Main_cause     382
Severity__       0
Affected_s       0
Magnitude        0
Centroid_X       0
Centroid_Y       0
"x"_if_act    4018
M_6              0
Total_annu       0
M_4              0
Total_an_1       0
Date_Began     326
Total_floo       0
Total_fl_1       0
F31           4029
F32           4029
F33           4029
F34           4029
F35           4029
F36           4029
dtype: int64

In [9]:
emdat.isnull().sum()

DisNo.                                           0
Historic                                         0
Classification Key                               0
Disaster Group                                   0
Disaster Subgroup                                0
Disaster Type                                    0
Disaster Subtype                                 0
External IDs                                 12522
Event Name                                   11548
ISO                                              0
Country                                          0
Subregion                                        0
Region                                           0
Location                                       798
Origin                                       12585
Associated Types                             13203
OFDA/BHA Response                                0
Appeal                                           0
Declaration                                      0
AID Contribution ('000 US$)                  16424
Magnitude                                    13510
Magnitude Scale                               6289
Latitude                                     15052
Longitude                                    15052
River Basin                                  15564
Start Year                                       0
Start Month                                     74
Start Day                                     1592
End Year                                         0
End Month                                      171
End Day                                       1507
Total Deaths                                  3283
No. Injured                                  10545
No. Affected                                  9047
No. Homeless                                 15547
Total Affected                                4276
Reconstruction Costs ('000 US$)              16879
Reconstruction Costs, Adjusted ('000 US$)    16879
Insured Damage ('000 US$)                    16189
Insured Damage, Adjusted ('000 US$)          16192
Total Damage ('000 US$)                      13571
Total Damage, Adjusted ('000 US$)            13599
CPI                                            216
Admin Units                                   8519
GADM Admin Units                              9082
Entry Date                                       0
Last Update                                      0
dtype: int64

In [ ]:
# cleaning and prepare EM-DAT 

# Filter the dataset to only include Floods
emdat_floods = emdat[emdat['Disaster Type'] == 'Flood'].copy()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
1,2026-0153-KEN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,KEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-09,2026-05-15
3,2026-0305-AFG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,AFG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-04,2026-05-11
11,2026-0310-COD,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,COD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-05,2026-05-20
16,2025-0647-GNQ,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2025-000145,NaN,GNQ,...,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,2025-08-05,2026-06-10
31,2025-0161-ARG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2025-000036,NaN,ARG,...,NaN,NaN,NaN,375000.0,375000.0,100.000000,NaN,NaN,2025-03-11,2026-06-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16900,2019-0504-NER,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,NER,...,NaN,NaN,NaN,NaN,NaN,79.410785,"[{""adm1_code"":2203,""adm1_name"":""Diffa""}]","[{""gid_1"":""NER.2_1"",""migration_date"":""2025-12-...",2019-10-24,2025-12-20
16901,2019-0515-TZA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,TZA,...,NaN,NaN,NaN,NaN,NaN,79.410785,"[{""adm2_code"":115085,""adm2_name"":""Handeni""}]","[{""gid_2"":""TZA.27.2_1"",""migration_date"":""2025-...",2019-10-28,2025-12-20
16902,2019-0526-SEN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2019-000118,NaN,SEN,...,NaN,NaN,NaN,NaN,NaN,79.410785,"[{""adm1_code"":1373,""adm1_name"":""Kaolack""},{""ad...","[{""gid_1"":""SEN.1_1"",""migration_date"":""2025-12-...",2019-10-29,2025-12-20
16911,2019-0576-FRA,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),HANZE:2112,NaN,FRA,...,NaN,NaN,NaN,NaN,NaN,79.410785,"[{""adm2_code"":16321,""adm2_name"":""Alpes-maritim...","[{""gid_2"":""FRA.13.2_1"",""migration_date"":""2025-...",2019-12-04,2025-12-20
16912,2019-0579-DJI,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,GLIDE:FF-2019-000161,NaN,DJI,...,NaN,NaN,NaN,NaN,NaN,79.410785,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...","[{""gid_1"":""DJI.1_2"",""migration_date"":""2025-12-...",2019-12-04,2025-12-20